import { expect, test } from '@playwright/test';
test('manager checklist edits preserve progress and dashboard resets only after confirmation', async ({ page }, testInfo) => {
  await page.goto('/crew/checklist');
  await expect(page.getByRole('combobox')).toHaveCount(4);
  await page.getByLabel('입고 상품 확인 상태').selectOption('done');
  await page.getByLabel('소비기한 확인 상태').selectOption('needs_manager');
  await page.reload();
  await expect(page.getByLabel('입고 상품 확인 상태')).toHaveValue('done');
  await page.getByRole('link', { name: '경영주로 전환' }).click();
  await page.getByRole('link', { name: '업무 관리', exact: true }).click();
  const first = page.getByRole('form', { name: '입고 상품 확인' });
  await first.getByLabel('업무 이름').fill('입고 수량과 포장 확인');
  await first.getByRole('button', { name: '항목 저장' }).click();
  await page.getByRole('button', { name: '업무 항목 추가' }).click();
  const create = page.getByRole('form', { name: '새 업무 항목' });
  await create.getByLabel('업무 이름').fill('인수인계 메모 확인');
  await create.getByLabel('업무 설명').fill('가상 매장의 메모를 확인해요.');
  await create.getByLabel('분류').fill('고객 응대');
  await create.getByRole('button', { name: '항목 등록' }).click();
  await page.getByRole('link', { name: '스토어 매니저로 전환' }).click();
  await page.getByRole('link', { name: '체크리스트', exact: true }).click();
  await expect(page.getByRole('combobox')).toHaveCount(5);
  await expect(page.getByLabel('입고 수량과 포장 확인 상태')).toHaveValue('done');
  await page.getByLabel('인수인계 메모 확인 상태').selectOption('done');
  await page.getByRole('link', { name: '경영주로 전환' }).click();
  await page.getByRole('link', { name: '대시보드', exact: true }).click();
  await expect(page.getByTestId('checklist-count')).toHaveText('2 / 5');
  await expect(page.getByTestId('needs-manager-count')).toHaveText('1');
  await expect(page.getByTestId('training-count')).toHaveText('0');
  await expect(page.getByTestId('question-count')).toHaveText('0');
  await expect(page.locator('main')).not.toContainText(/점수|순위|적합도/);
  await page.screenshot({ path: `docs/evidence/dashboard-${testInfo.project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: '데모 데이터 초기화', exact: true }).click();
  await page.getByRole('button', { name: '취소', exact: true }).click();
  await expect(page.getByTestId('checklist-count')).toHaveText('2 / 5');
  await page.getByRole('button', { name: '데모 데이터 초기화', exact: true }).click();
  await page.getByRole('button', { name: '초기화하기', exact: true }).click();
  await expect(page.getByTestId('checklist-count')).toHaveText('0 / 4');
  await expect(page.getByTestId('needs-manager-count')).toHaveText('0');
});
