import { expect, test } from '@playwright/test';
import { trainingSteps } from '../../src/features/training/training-data';

test('manager checklist edits preserve progress and reset requires confirmation', async ({ page }, testInfo) => {
  await page.goto('/crew/checklist');
  await expect(page.getByRole('combobox')).toHaveCount(4);
  await page.getByLabel('입고 상품 확인 상태').selectOption('done');
  await page.getByLabel('소비기한 확인 상태').selectOption('needs_manager');
  await page.reload();
  await expect(page.getByLabel('입고 상품 확인 상태')).toHaveValue('done');
  await page.getByRole('link', { name: '경영주 관리', exact: true }).click();
  await page.getByRole('link', { name: '체크리스트 설정', exact: true }).first().click();
  await page.locator('summary').filter({ hasText: '입고 상품 확인' }).click();
  const first = page.getByRole('form', { name: '입고 상품 확인 수정' });
  await first.getByLabel('항목 이름').fill('입고 수량과 포장 확인');
  await first.getByRole('button', { name: '항목 저장' }).click();
  await page.getByRole('button', { name: '체크리스트 항목 추가' }).click();
  const create = page.getByRole('form', { name: '새 체크리스트 항목' });
  await create.getByLabel('항목 이름').fill('인수인계 메모 확인');
  await create.getByLabel('확인할 내용').fill('가상 매장의 메모를 확인해요.');
  await create.getByLabel('분류').fill('고객 응대');
  await create.getByRole('button', { name: '항목 등록' }).click();
  await expect(page.getByRole('status').filter({ hasText: '새 항목을 체크리스트에 등록했어요.' })).toBeVisible();
  await page.getByRole('link', { name: '스토어 매니저 화면 보기' }).click();
  await expect(page.getByRole('combobox')).toHaveCount(5);
  await expect(page.getByLabel('입고 수량과 포장 확인 상태')).toHaveValue('done');
  await page.getByLabel('인수인계 메모 확인 상태').selectOption('done');
  await expect(page.getByRole('progressbar', { name: '업무 완료 현황' })).toHaveAttribute('value', '2');
  await page.getByRole('button', { name: '데모 데이터 초기화', exact: true }).click();
  await page.getByRole('button', { name: '취소', exact: true }).click();
  await expect(page.getByRole('combobox')).toHaveCount(5);
  await expect(page.getByLabel('소비기한 확인 상태')).toHaveValue('needs_manager');
  await page.getByRole('button', { name: '데모 데이터 초기화', exact: true }).click();
  await page.getByRole('button', { name: '초기화하기', exact: true }).click();
  await expect(page.getByRole('combobox')).toHaveCount(4);
  await expect(page.getByRole('progressbar', { name: '업무 완료 현황' })).toHaveAttribute('value', '0');
  await page.getByRole('link', { name: '경영주 관리', exact: true }).click();
  await expect(page.getByTestId('training-count')).toHaveText('0회');
  await expect(page.getByTestId('training-average')).toHaveText('—완료 후 표시');
  await expect(page.getByRole('heading', { name: '아직 연습 기록이 없어요' })).toBeVisible();
  await expect(page.getByRole('link', { name: '업무 관리', exact: true })).toHaveCount(0);
  await page.screenshot({ path: `docs/evidence/dashboard-${testInfo.project.name}.png`, fullPage: true });
});

test('manager reviews complete test scores, stage answers and in-progress records after refresh', async ({ page }) => {
  await page.goto('/crew/simulation?mode=test');
  await page.getByLabel('테스트 참여자 별칭').fill('지원자 A');
  await page.getByRole('button', { name: '테스트 시작하기', exact: true }).click();
  for (const [index, step] of trainingSteps.entries()) {
    const choice = step.choices.find(item => index === 0 ? item.id !== step.correctChoiceId : item.id === step.correctChoiceId)!;
    await page.getByRole('group', { name: 'POS 행동 선택' }).getByRole('button', { name: new RegExp(choice.label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')) }).click();
    await page.getByRole('button', { name: index === trainingSteps.length - 1 ? '제출하고 점수 보기' : '답 제출하고 다음 단계', exact: true }).click();
  }
  await expect(page.getByRole('heading', { name: '끝까지 해냈어요!' })).toBeVisible();
  await page.getByRole('button', { name: '다시 연습하기' }).click();
  await page.getByRole('link', { name: '경영주 관리', exact: true }).click();
  await expect(page).toHaveURL(/\/manager\/dashboard$/);
  await page.reload();
  await expect(page.getByTestId('training-count')).toHaveText('1회');
  await expect(page.getByTestId('training-average')).toContainText('92');
  await expect(page.getByText('진행 중', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '구인 테스트', exact: true }).click();
  const records = page.locator('details').filter({ has: page.locator('summary', { hasText: '지원자 A' }) });
  await expect(records).toHaveCount(1);
  await records.locator('summary').click();
  await expect(records.getByRole('listitem')).toHaveCount(trainingSteps.length);
  await expect(records.getByText('오답', { exact: true })).toHaveCount(1);
  await expect(records.getByRole('link', { name: /교육 근거/ })).toHaveCount(trainingSteps.length);
  await expect(page.getByText('채용 합격', { exact: true })).toHaveCount(0);
});
