import { expect, test } from '@playwright/test';
test('edits all fields and creates a missing rule, retaining both after refresh', async ({ page }, testInfo) => {
  await page.goto('/');
  await page.getByRole('link', { name: /경영주로 시작/ }).click();
  const form = page.getByRole('form', { name: '행사 문의는 POS 확인 후 안내' });
  await form.getByLabel('규칙 제목').fill('행사 안내 순서');
  await form.getByLabel('규칙 내용').fill('조회 후 고객에게 행사 조건을 차근차근 안내합니다.');
  await form.getByLabel('분류').fill('고객 응대');
  await form.getByLabel('예외 처리').fill('불명확한 조건은 경영주에게 문의합니다.');
  await form.getByRole('button', { name: '규칙 저장' }).click();
  const saved = page.getByRole('form', { name: '행사 안내 순서' });
  await expect(saved.getByRole('status')).toContainText('저장했어요');
  await page.reload();
  await expect(saved.getByText('v2', { exact: true })).toBeVisible();
  await expect(saved.getByLabel('규칙 내용')).toHaveValue('조회 후 고객에게 행사 조건을 차근차근 안내합니다.');
  await expect(saved.getByLabel('분류')).toHaveValue('고객 응대');
  await expect(saved.getByLabel('예외 처리')).toHaveValue('불명확한 조건은 경영주에게 문의합니다.');
  await page.getByRole('button', { name: '새 규칙 추가', exact: true }).click();
  const create = page.getByRole('form', { name: '새 규칙 작성' });
  await create.getByLabel('규칙 제목').fill('우산 보관');
  await create.getByLabel('규칙 내용').fill('가상 매장의 우산은 입구 보관함에 둡니다.');
  await create.getByLabel('분류').fill('매장 안내');
  await create.getByLabel('예외 처리').fill('분실물은 경영주에게 전달합니다.');
  await create.getByRole('button', { name: '규칙 등록' }).click();
  await page.reload();
  await expect(page.getByRole('form', { name: '우산 보관' })).toBeVisible();
  await page.screenshot({ path: `docs/evidence/manual-${testInfo.project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: '스토어 매니저로 전환' }).click();
  await expect(page.getByRole('heading', { name: '오늘의 첫걸음' })).toBeVisible();
});
