import { expect, test } from '@playwright/test';
test('answers from the latest rule and preserves unsupported questions', async ({ page }, testInfo) => {
  await page.goto('/crew/questions');
  await page.getByLabel('매장에 궁금한 점').fill('직원 급여 정산 계좌');
  await page.getByRole('button', { name: '질문하기', exact: true }).click();
  await expect(page.getByTestId('question-log').first()).toContainText('경영주 확인 필요');
  await page.getByRole('link', { name: '경영주 관리', exact: true }).click();
  await page.getByRole('link', { name: '추가 매장 규칙', exact: true }).click();
  const rule = page.getByRole('form', { name: '행사 문의는 POS 확인 후 안내' });
  await rule.getByLabel('규칙 내용').fill('조회 후 행사 조건을 고객에게 차근차근 안내해 주세요.');
  await rule.getByRole('button', { name: '규칙 저장' }).click();
  await page.goto('/crew/questions');
  await page.locator('summary').filter({ hasText: '매장 추가 규칙' }).click();
  await page.getByRole('button', { name: '행사 문의는 POS 확인 후 안내', exact: true }).click();
  await expect(page.getByTestId('question-log').first()).toContainText('조회 후 행사 조건을 고객에게 차근차근 안내해 주세요.');
  await expect(page.getByTestId('question-log').first()).toContainText('v2');
  await expect(page.getByTestId('question-log').first()).toContainText('3,000원');
  await expect(page.getByTestId('question-log').first()).toContainText('데모 모드');
  await page.reload();
  await expect(page.getByTestId('question-log')).toHaveCount(2);
  await expect(page.getByTestId('question-log').last()).toContainText('경영주 확인 필요');
  await page.screenshot({ path: `docs/evidence/qa-${testInfo.project.name}.png`, fullPage: true });
});
test('general advice is useful and explicitly distinct from manual evidence with categorized examples', async ({ page }) => {
  await page.goto('/crew/questions');
  await page.getByRole('button', { name: '첫 출근이라 긴장돼요', exact: true }).click();
  const latest = page.getByTestId('question-log').first();
  await expect(latest).toContainText('일반 AI 안내');
  await expect(latest).toContainText('메모');
  await expect(latest).not.toContainText('매뉴얼 근거 있음');
  await page.getByRole('button', { name: '응대·소통', exact: true }).click();
  await expect(page.getByRole('button', { name: '동료와 친해지는 방법', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'POS·상품', exact: true }).click();
  await page.getByRole('button', { name: '판매 보류', exact: true }).click();
  await expect(latest).toContainText('매뉴얼 근거 있음');
  await expect(latest.getByText('답변 근거 ·', { exact: false })).toBeVisible();
});
