'use client';
import Link from 'next/link';
import { ArrowUpRight, MessageCircle } from 'lucide-react';
import { useStore, StoreLoading } from '@/data/store-provider';
import { summarizeDashboard } from './dashboard-summary';
import { ResetData } from '@/components/reset-data';
export function Dashboard() {
  const store = useStore(); if (!store) return <StoreLoading/>;
  const summary = summarizeDashboard(store.state);
  return <><div className="page-heading"><p className="eyebrow">MAKE THE NEXT FIRST DAY EASIER</p><h1>우리 매장의 오늘</h1><p>{store.state.store.name} · 연습과 업무에서 필요한 도움을 살펴봐요.</p></div><dl className="dashboard-stats"><div><dt>완료한 연습</dt><dd data-testid="training-count">{summary.completedTraining}</dd><span>재도전을 포함한 완료 횟수</span></div><div><dt>완료한 업무</dt><dd data-testid="checklist-count">{summary.checklistDone} / {summary.checklistTotal}</dd><span>현재 등록된 업무 기준</span></div><div><dt>누적 질문</dt><dd data-testid="question-count">{summary.questions}</dd><span>이 브라우저에 남긴 질문</span></div><div><dt>확인 필요</dt><dd data-testid="needs-manager-count">{summary.needsManager}</dd><span>미해결 질문 + 확인 요청 업무</span></div></dl>
    <div className="dashboard-grid"><section aria-labelledby="unresolved-heading"><div className="section-heading"><h2 id="unresolved-heading">매뉴얼에 보완할 질문</h2><span className="pill">{summary.unresolved.length}개</span></div>{!summary.unresolved.length ? <div className="empty-state"><MessageCircle size={26} aria-hidden/><h3>아직 미해결 질문이 없어요</h3><p>규칙에서 답을 찾지 못한 질문이 이곳에 모여요.</p></div> : <ul className="review-list">{summary.unresolved.map(question => <li key={question.id}><span className="pill warning-pill">경영주 확인 필요</span><h3>{question.question}</h3><p>질문 당시 답할 규칙이 없거나 근거가 명확하지 않았어요.</p><Link className="text-link" href="/manager/manual">매뉴얼 보완하기 <ArrowUpRight size={14} aria-hidden/></Link></li>)}</ul>}</section>
    <section aria-labelledby="needs-heading"><div className="section-heading"><h2 id="needs-heading">함께 확인할 업무</h2><span className="pill">{summary.needsItems.length}개</span></div>{!summary.needsItems.length ? <div className="empty-state"><h3>현재 확인 요청이 없어요</h3><p>체크리스트에서 도움이 필요한 항목을 볼 수 있어요.</p></div> : <ul className="review-list">{summary.needsItems.map(item => <li key={item.id}><span className="small-note">{item.category}</span><h3>{item.title}</h3><p>{item.description}</p></li>)}</ul>}</section></div>
    <section className="recent-training" aria-labelledby="recent-heading"><div className="section-heading"><h2 id="recent-heading">최근 연습 기록</h2><span className="small-note">완료와 진행 상태를 확인해요</span></div>{!summary.sessions.length ? <p className="empty-state">스토어 매니저가 연습을 시작하면 기록이 나타나요.</p> : <div className="table-scroll"><table><thead><tr><th scope="col">연습 상황</th><th scope="col">진행 상태</th><th scope="col">사용한 규칙</th><th scope="col">시작 시각</th></tr></thead><tbody>{[...summary.sessions].reverse().map(session => <tr key={session.id}><th scope="row">{session.scenario.title}{session.previousAttemptId && <span className="small-note"> · 재도전</span>}</th><td>{session.status === 'completed' ? '연습 완료' : '진행 중'}</td><td>{session.snapshot.rules.filter(rule => session.scenario.ruleIds.includes(rule.id)).map(rule => `v${rule.version}`).join(', ')}</td><td><time dateTime={session.createdAt}>{new Date(session.createdAt).toLocaleString('ko-KR')}</time></td></tr>)}</tbody></table></div>}</section><ResetData/>
  </>;
}
